import '../packet/domain/action_packet.dart';

/// Exports Action Packet models into structured GitHub Flavored Markdown (GFM).
class MarkdownExporter {
  /// Converts an [ActionPacketModel] into a clean GFM markdown report.
  static String toMarkdown(ActionPacketModel packet) {
    final sb = StringBuffer();

    sb.writeln('# ECHO Action Packet: ${packet.title}');
    sb.writeln();
    sb.writeln('| Property | Value |');
    sb.writeln('| --- | --- |');
    sb.writeln('| **Packet ID** | `${packet.id}` |');
    sb.writeln('| **Status** | `${packet.status.toUpperCase()}` |');
    sb.writeln('| **Priority** | **${packet.priority.toUpperCase()}** |');
    sb.writeln('| **Category** | ${packet.category} |');
    sb.writeln('| **Confidence State** | ${packet.confidenceState} |');
    sb.writeln('| **Created At** | ${packet.createdAt.toIso8601String()} |');
    sb.writeln();

    sb.writeln('## Executive Summary');
    sb.writeln('> ${packet.summary}');
    sb.writeln();

    sb.writeln('## Priority Rationale');
    sb.writeln(packet.priorityReason);
    sb.writeln();

    if (packet.observations.isNotEmpty) {
      sb.writeln('## Observed Facts');
      for (final obs in packet.observations) {
        sb.writeln('- **Fact**: ${obs.fact}');
      }
      sb.writeln();
    }

    if (packet.inferences.isNotEmpty) {
      sb.writeln('## Inferences & Diagnostic Reasoning');
      for (final inf in packet.inferences) {
        sb.writeln('- ${inf.inference}');
      }
      sb.writeln();
    }

    if (packet.checklist.isNotEmpty) {
      sb.writeln('## Operational Checklist');
      for (final item in packet.checklist) {
        final checked = item.isCompleted ? '[x]' : '[ ]';
        sb.writeln('- $checked ${item.text}');
      }
      sb.writeln();
    }

    sb.writeln('---');
    sb.writeln('*Generated by ECHO Evidence Handoff Orchestrator*');

    return sb.toString();
  }
}
